realtime_mlops:
  target: local
  outputs:
    dev:
      type: spark
      method: thrift
      host: "spark-thrift"
      port: 10000
      user: "spark"
      pass: ""
      schema: "default"
    local:
      type: spark
      method: thrift
      host: "localhost"
      port: 10000
      user: "spark"
      pass: ""
      schema: "default"

