groups:
  - name: test_alerts
    rules:
      - alert: AlwaysOn
        expr: vector(1)
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Test Alert"
          description: "This is a test alert to check Slack notifications."
