global:
  scrape_interval: 15s      # Default scrape interval
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka Exporter: adjust the target host/port as needed.
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Node Exporter: optional, if you run node-exporter for host metrics.
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # JMX Exporter: adjust the target host/port as needed.
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9404']

# Alerting rules
rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"




